#defaults:
#  - override hydra/launcher: joblib

hydra:
  job:
    chdir: false

target:
  global_centering: false
  custom_samples: true
  temperature: 0.1  # 0.1 or 1 are two good options


flow:
  dim: 2
  nodes: 4
  n_layers: 4
  identity_init: true
  type: [proj,nice]  # vector_scale  vector_scale nice proj   proj_v2
  kwargs:
    proj_v2:
      global_frame: false
      process_flow_params_jointly: false
      gram_schmidt: false
      mlp_function_units: [16,]
  act_norm: true
  fast_compile: true
  compile_n_unroll: 1
  egnn:
    emile_net: false
    mlp_units: [32,32]
    n_layers: 3
    normalize_by_norms: true
    variance_scaling_init: 0.001
    tanh: false
    agg: mean
    phi_x_max: 1.0
    h:
      linear_softmax: true
      share_h: true
  transformer: # for proj_v2 flow.
    mlp_units: [32,32]
    num_heads: 3
    key_size: 4
    w_init_scale: 0.1
    n_layers: 3


training:
  lr: 4e-4
  use_64_bit: false
  optimizer_name: adam
  n_epoch: 50
  batch_size: 100
  plot_batch_size: 256
  max_global_norm: null
  seed: 0
  reload_aug_per_epoch: true
  train_set_size: 1000
  test_set_size: 1000
  n_plots: 6
  n_checkpoints: 0
  n_eval: 10
  K_marginal_log_lik: 20
  save: true
  save_dir: dw4_results

logger:
#  list_logger: null
  wandb:
    name: dw4_${flow.type}
    project: fab
    entity: flow-ais-bootstrap
    tags: [dw4]

