#defaults:
#  - override hydra/launcher: joblib

hydra:
  job:
    chdir: false

flow:
  dim: 2
  nodes: 4
  n_layers: 4
  identity_init: true
  type: nice  # vector_scale_shift  vector_scale nice proj   proj_v2
  fast_compile: true
  compile_n_unroll: 1
  egnn:
    mlp_units: [4,]
    n_layers: 2
    h:
      linear_softmax: true
      share_h: true
  transformer: # for proj_v2 flow.
    mlp_units: [4,]


training:
  lr: 1e-3
  n_epoch: 200
  batch_size: 20
  plot_batch_size: 128
  max_global_norm: null
  seed: 0
  reload_aug_per_epoch: true
  train_set_size: 1000
  test_set_size: 1000
  n_plots: 4
  n_checkpoints: 2
  n_eval: 4
  K_marginal_log_lik: 8
  save: true
  save_dir: dw4_results

logger:
#  list_logger: null
  wandb:
    name: dw4_${flow.type}
    project: fab
    entity: flow-ais-bootstrap
    tags: [dw4]

