#defaults:
#  - override hydra/launcher: joblib

hydra:
  job:
    chdir: false

flow:
  dim: 3
  nodes: 29
  n_layers: 4
  identity_init: true
  type: nice  # vector_scale_shift  vector_scale nice proj   proj_v2
  fast_compile: true
  compile_n_unroll: 1
  egnn:
    mlp_units: [64, 64]
    n_layers: 3
    h:
      linear_softmax: true
      share_h: true
  transformer: # for proj_v2 flow.
    mlp_units: [64,64]


training:
  lr: 1e-4
  n_epoch: 100
  batch_size: 32
  plot_batch_size: 32
  max_global_norm: 10_000
  seed: 0
  reload_aug_per_epoch: true
  train_set_size: null
  test_set_size: null
  n_plots: 6
  n_checkpoints: 8
  n_eval: 10
  K_marginal_log_lik: 20
  save: true
  save_dir: qm9pos_results

logger:
#  list_logger: null
  wandb:
    name: qm9pos_${flow.type}
    project: fab
    entity: flow-ais-bootstrap
    tags: [qm9pos]

